import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeModeScript } from "flowbite-react";
import { DarkThemeToggle, Flowbite } from "flowbite-react";
import NavLinks from "../components/nav-links/nav-links";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next-test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className}>
        <nav className="flex justify-between">
          <NavLinks />
          <div className="flex justify-end items-center gap-5 p-2">
            <p>Toggle theme</p>
            <Flowbite>
              <DarkThemeToggle />
            </Flowbite>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
